networks:
  aziona_group_network:

services:
  ############################# Django App ##############################
  django:
    build: .
    container_name: aziona_group_app
    image: aziona_group:latest
    command: python3 manage.py runserver  0.0.0.0:8000 --insecure
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - .:/aziona_group
      - ./docker/aziona_group/ssl:/etc/ssl
    ports:
      - "8000:8000"
    networks:
      - aziona_group_network

    ########################### Caddy (Reverse Proxy) ############################
  caddy:
    image: caddy:latest
    container_name: caddy_reverse_proxy_aziona_group
    restart: unless-stopped
    ports:
      - "443:443"  # HTTPS
      - "80:80"    # HTTP
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - aziona_group_network
    depends_on:
      django:
        condition: service_started
volumes:
  caddy_data: {}
  caddy_config: {}